const express=require('express');const app=express();app.use(express.json({limit:'15mb'}));app.use(express.static('public'));
function safeMetaResult(value){if(Array.isArray(value))return value.map(safeMetaResult);if(value&&typeof value==='object'){return Object.fromEntries(Object.entries(value).filter(([key])=>!['access_token','next','previous'].includes(key)).map(([key,item])=>[key,safeMetaResult(item)]))}return value}
const G='https://graph.facebook.com/v24.0';const runtime={};function cfg(){return{token:runtime.META_ACCESS_TOKEN||process.env.META_ACCESS_TOKEN,account:(runtime.META_AD_ACCOUNT_ID||process.env.META_AD_ACCOUNT_ID||'').replace(/^act_/,''),page:runtime.META_PAGE_ID||process.env.META_PAGE_ID,openai:runtime.OPENAI_API_KEY||process.env.OPENAI_API_KEY}}
async function meta(path,opt={}){const c=cfg();if(!c.token)throw Error('ยังไม่ได้ตั้ง META_ACCESS_TOKEN ใน Railway');const u=new URL(G+path);u.searchParams.set('access_token',c.token);const r=await fetch(u,{...opt,headers:{'content-type':'application/json',...(opt.headers||{})}});const j=await r.json();if(!r.ok)throw Error(j?.error?.message||'Meta API error');return safeMetaResult(j)}
app.get('/health',(q,s)=>s.json({ok:true}));app.post('/api/settings',(q,s)=>{try{const b=q.body||{};if(b.metaToken)runtime.META_ACCESS_TOKEN=String(b.metaToken).trim();if(b.adAccount)runtime.META_AD_ACCOUNT_ID=String(b.adAccount).trim();if(b.openaiKey)runtime.OPENAI_API_KEY=String(b.openaiKey).trim();s.json({ok:true})}catch(e){s.status(400).json({error:e.message})}});app.get('/api/config',(q,s)=>{const c=cfg();s.json({meta:!!(c.token&&c.account&&c.page),openai:!!c.openai,account:c.account?'act_'+c.account:'',page:c.page||''})});
app.get('/api/meta/test',async(q,s)=>{try{const c=cfg();s.json({ok:true,data:await meta('/act_'+c.account+'?fields=id,name,account_status,currency')})}catch(e){s.status(400).json({error:e.message})}});
app.get('/api/meta/pages',async(q,s)=>{try{s.json(await meta('/me/accounts?fields=id,name,picture&limit=100'))}catch(e){s.status(400).json({error:e.message})}}); app.get('/api/meta/page',async(q,s)=>{try{const c=cfg();s.json(await meta('/'+(q.query.pageId||c.page)+'?fields=id,name,picture'))}catch(e){s.status(400).json({error:e.message})}});
app.get('/api/meta/posts',async(q,s)=>{try{const c=cfg(),p=q.query.pageId||c.page;s.json(await meta('/'+p+'/posts?fields=id,message,created_time,permalink_url,full_picture,attachments{media,type,url}&limit=50'))}catch(e){s.status(400).json({error:e.message})}});
app.get('/api/meta/ads',async(q,s)=>{try{const c=cfg();s.json(await meta('/act_'+c.account+'/ads?fields=id,name,status,effective_status,creative{id,effective_object_story_id},adset{id,name,daily_budget},campaign{id,name},insights.date_preset(today){spend,clicks,cpc}&limit=100'))}catch(e){s.status(400).json({error:e.message})}});
app.post('/api/meta/status',async(q,s)=>{try{const{id,status}=q.body;if(!id||!['ACTIVE','PAUSED'].includes(status))throw Error('ข้อมูลไม่ครบ');s.json(await meta('/'+id,{method:'POST',body:JSON.stringify({status})}))}catch(e){s.status(400).json({error:e.message})}});
app.post('/api/meta/create-existing-post',async(q,s)=>{try{const c=cfg(),b=q.body;c.page=b.pageId||c.page;if(!b.name||!b.postId||!b.dailyBudget)throw Error('กรอกชื่อ เลือกโพสต์ และงบให้ครบ');const camp=await meta('/act_'+c.account+'/campaigns',{method:'POST',body:JSON.stringify({name:b.name+' Campaign',objective:'OUTCOME_TRAFFIC',special_ad_categories:[],status:'PAUSED'})});const adset=await meta('/act_'+c.account+'/adsets',{method:'POST',body:JSON.stringify({name:b.name+' Ad Set',campaign_id:camp.id,daily_budget:Math.round(+b.dailyBudget*100),billing_event:'IMPRESSIONS',optimization_goal:'LINK_CLICKS',bid_strategy:'LOWEST_COST_WITHOUT_CAP',targeting:{geo_locations:{countries:['TH']},age_min:+(b.ageMin||18),age_max:+(b.ageMax||65)},status:'PAUSED'})});const cr=await meta('/act_'+c.account+'/adcreatives',{method:'POST',body:JSON.stringify({name:b.name+' Existing Post',object_story_id:b.postId})});const ad=await meta('/act_'+c.account+'/ads',{method:'POST',body:JSON.stringify({name:b.name,adset_id:adset.id,creative:{creative_id:cr.id},status:'PAUSED'})});s.json({ok:true,campaign:camp.id,adset:adset.id,creative:cr.id,ad:ad.id,pageId:c.page,postId:b.postId,subId:b.subId||ad.id})}catch(e){s.status(400).json({error:e.message})}});
app.post('/api/affiliate/parse',async(q,s)=>{try{const text=q.body.csv;if(!text)throw Error('ไม่มีไฟล์ CSV');const lines=text.replace(/^\uFEFF/,'').split(/\r?\n/).filter(Boolean);const parse=l=>{let a=[],v='',qq=false;for(let i=0;i<l.length;i++){let c=l[i];if(c=='"'&&l[i+1]=='"'){v+='"';i++}else if(c=='"')qq=!qq;else if(c==','&&!qq){a.push(v);v=''}else v+=c}a.push(v);return a};const head=parse(lines[0]);const rows=lines.slice(1).map(x=>{const v=parse(x),o={};head.forEach((h,i)=>o[h.trim()]=v[i]||'');return o});const find=(o,keys)=>{for(const k of Object.keys(o)){const z=k.toLowerCase();if(keys.some(x=>z.includes(x)))return o[k]}return''};const data=rows.map(o=>({clickTime:find(o,['เวลาคลิก','click time']),orderTime:find(o,['เวลาที่สั่ง','order time']),product:find(o,['ชื่อสินค้า','product name']),productId:find(o,['รหัสสินค้า','product id','item id']),commission:find(o,['ค่าคอมมิชชั่นสุทธิ','net commission']),status:find(o,['สถานะ','status']),sub1:find(o,['sub_id1','sub id1','subid1']),sub2:find(o,['sub_id2','sub id2','subid2']),sub3:find(o,['sub_id3','sub id3','subid3']),sub4:find(o,['sub_id4','sub id4','subid4']),sub5:find(o,['sub_id5','sub id5','subid5'])}));const total=data.reduce((n,x)=>n+(parseFloat(String(x.commission).replace(/[^0-9.-]/g,''))||0),0);s.json({ok:true,count:data.length,totalCommission:total,data})}catch(e){s.status(400).json({error:e.message})}});
app.post('/api/ai',async(q,s)=>{try{const key=cfg().openai;if(!key)throw Error('ยังไม่ได้ตั้ง OPENAI_API_KEY');const r=await fetch('https://api.openai.com/v1/responses',{method:'POST',headers:{Authorization:'Bearer '+key,'Content-Type':'application/json'},body:JSON.stringify({model:'gpt-5.6-luna',input:'วิเคราะห์โฆษณา Shopee Affiliate แบบกระชับ ห้ามสั่งใช้เงินเอง ข้อมูล: '+JSON.stringify(q.body)})});const j=await r.json();if(!r.ok)throw Error(j.error?.message||'OpenAI error');s.json({ok:true,text:j.output_text||''})}catch(e){s.status(400).json({error:e.message})}});
app.listen(Number(process.env.PORT||3000),'0.0.0.0',()=>console.log('Shopee AFF AI Ads listening'));